CREATE TABLE DataSet
   (session_id STRING,
	referrer_site STRING,
	publisher_id STRING,  
	network_id STRING, 
	domain_id STRING, 
	domain_identifier STRING, 
	slot_type_id STRING,  
	ad_request_count STRING, 
	ad_served_count STRING, 
	is_yume_blacklisted STRING,  
	is_network_blacklisted STRING, 
	is_not_in_network_white_listed STRING,
	is_not_yume_whitelisted STRING,  
	is_unknown_domain_for_yume STRING,  
	is_unknown_domain_for_in_network STRING,
	ad_visibility_violation STRING,
	ad_duration_violation STRING, 
	un_paid_ad_count STRING, 
	publisher_channel_id STRING,  
	publisher_page_id STRING,
	content_video_id STRING,  
	content_video_identifier STRING,
	content_profile_id STRING,
	country_code STRING,
	state_code STRING,
	city_name STRING,
	census_data_DMA_id STRING,  
	is_wthout_pre_fetch STRING,
	is_pre_fetch_request STRING,
	published_player_identifier STRING,   
	content_playlist_identifier STRING,  
	delivery_point_id STRING,
	device_make_name STRING,
	device_model_name STRING,
	os_name STRING,
	os_version_name STRING,
	browser_name STRING,
	browser_version_name STRING,
	service_provider_name STRING,
	key_values STRING,
	sdk_version STRING,
	back_fill STRING,   
	session_id_dup STRING,
	requested_date STRING,
	cookie STRING,  
	ip_address STRING,
	device_make_id INT,
	device_model_id INT,
	os_id INT,
	os_version_id INT,
	browser_id INT,
	browser_version_id INT,
	service_provider_id INT,
	network_key_value STRING,
	player_size_id INT,
	player_location_id INT,
	page_fold_id INT,
	ad_visibility_id INT,  
	play_type STRING,
	ovp_type STRING, 
	ovp_version STRING,
	ovp_plugin STRING,
	hid INT,   
	num_of_devices INT,  
	is_on_premises INT,
	audience_segments STRING,
	advertisement_id INT,
	placement_id INT,   
	behaviour_cookie STRING,
	remarketing_cookie STRING,
	json_data STRING) 
 ROW FORMAT DELIMITED FIELDS TERMINATED BY '\;'
 STORED AS TEXTFILE
 LOCATION 's3://BUCKET_NAME/HIVE_INPUT_DIR/';
 LOAD DATA INPATH 's3://' INTO TABLE DataSet;
create temporary function extractIdentifier as 'com.example.hive.udf.ExtractIdentifier';
	


